version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1
    ports:
      - "5050:5050"
    depends_on:
      - redis
    command: python app.py


  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
    ports:
      - "5070:5070"
    command: python app.py


  redis:
    image: redis:latest
    hostname: redis
    volumes:
      - redis_data:/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"

networks:
  default:
    external:
      name: kafka-network

volumes:
  redis_data:
