version: '3'

services:

  generator:
    container_name: generator
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1
    volumes:
      - ./generator:/app
    ports:
      - "5050:5050"
    depends_on:
      - redis
    command: python app.py


  detector:
    container_name: detector
    build: ./detector
    volumes:
      - ./detector:/app
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
    ports:
      - "5070:5070"
    command: python app.py


  redis:
    image: redis:latest
    hostname: redis
    volumes:
      - redis_data:/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432


volumes:
  redis_data:
  dbdata:
  gen_code:
  det_code:


networks:
  default:
    external:
      name: kafka-network
